from enum import StrEnum


class Permission(StrEnum):
    USERS_CREATE = "USERS_CREATE"
    USERS_READ = "USERS_READ"
    USERS_UPDATE = "USERS_UPDATE"
    USERS_DELETE = "USERS_DELETE"
    ITEMS_CREATE = "ITEMS_CREATE"
    ITEMS_READ = "ITEMS_READ"
    ITEMS_UPDATE = "ITEMS_UPDATE"
    ITEMS_DELETE = "ITEMS_DELETE"
